name: The  Open  Film  School
favicon: null
layout_spectrum: 0.48328
typography_spectrum: 0.27372882165946066
title: The Open Film School
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f0fb01'
    - '#060708'
    - '#ffffff'
    - '#b5bf09'
    - '#6c7204'
  brandStrength: 0
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
