name: The  Open  Film  School
favicon: null
layout_spectrum: 0.25181
typography_spectrum: 0.00812
title: The Open Film School
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f0f0f0'
    - '#242424'
    - '#666666'
    - '#868686'
    - '#bbbbbb'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
