name: The  Open  Film  School
favicon: null
layout_spectrum: 1
typography_spectrum: 0
title: The Open Film School
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0fffef'
    - '#002fff'
    - '#ff2f00'
    - '#afafaf'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 0
purpose: []
