name: The  Open  Film  School
favicon: null
layout_spectrum: 0.23917
typography_spectrum: 0.00812
title: The Open Film School
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000606'
    - '#880400'
    - '#008a01'
    - '#e54400'
    - '#c5bd02'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
