typography_spectrum: 0.975020311307162
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.32302755815908313
  lightness: 0.9904217375442386
  saturation: 0.31603349349461496
  rhythmicContrast: 0.19927296438254416
opengraph:
  image: null
  type: null
  appId: 'https://www.facebook.com/theopenfilmschool/'
layout_spectrum: 0.4563593491911888
analytics:
  google: null
  facebook: null
  twitter: null
name: The  Open  Film  School
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: 'Documentary '
    id: aa8a1ea0-29c3-449a-8224-d7adb925e58c
    type: content
  - name: Screenwriting
    id: a6387259-4974-4fa9-b705-44df17fc1956
    type: content
  - name: Total Filmmaking
    id: 666ea6f1-cac6-45e7-8413-7fdbc44bbde3
    type: content
  - name: About Us
    id: 990b0e4d-6bb6-4029-bd58-fbf0c03209c1
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8e3f56a4-ebba-454c-a21e-9e6b038cca4c.jpg
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: The Open Film School
description: For the love of filmmaking
purpose: []
