typography_spectrum: 0.74639
color:
  brandColors:
    - '#00000a'
    - '#dc0c0c'
    - '#dec10d'
    - '#067483'
    - '#06b3ae'
  brandStrength: 0.5
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
name: The  Open  Film  School
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: 'Documentary '
    id: aa8a1ea0-29c3-449a-8224-d7adb925e58c
    type: content
  - name: Screenwriting
    id: a6387259-4974-4fa9-b705-44df17fc1956
    type: content
  - name: Total Filmmaking
    id: 666ea6f1-cac6-45e7-8413-7fdbc44bbde3
    type: content
favicon: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: The Open Film School
description: For the love of filmmaking
purpose: []
