name: The  Open  Film  School
favicon: null
layout_spectrum: 0.60018
typography_spectrum: 0.00812
title: The Open Film School
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00001c'
    - '#f2eec9'
    - '#950622'
    - '#625567'
    - '#8d8382'
  brandStrength: 1
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
