name: The  Open  Film  School
favicon: null
layout_spectrum: 0.73556
typography_spectrum: 0.27372882165946066
title: The Open Film School
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00001c'
    - '#f1edc8'
    - '#950622'
    - '#7c6f78'
    - '#aca394'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
