layout_spectrum: 0.6488942075520754
typography_spectrum: 0.5547778340987861
color:
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
  brandStrength: 0.6174267821479589
  lightness: 0.1699889984447509
  saturation: 0.9617323640268296
  rhythmicContrast: 0.05590964527800679
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: The  Open  Film  School
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: 'Documentary '
    id: aa8a1ea0-29c3-449a-8224-d7adb925e58c
    type: content
  - name: Screenwriting
    id: a6387259-4974-4fa9-b705-44df17fc1956
    type: content
  - name: Total Filmmaking
    id: 666ea6f1-cac6-45e7-8413-7fdbc44bbde3
    type: content
  - name: About Us
    id: 990b0e4d-6bb6-4029-bd58-fbf0c03209c1
    type: content
favicon: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: The Open Film School
description: For the love of filmmaking
purpose: []
