name: The  Open  Film  School
favicon: null
layout_spectrum: 1
typography_spectrum: 0
title: The Open Film School
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0f0f0f'
    - '#9a9c9b'
    - '#414141'
    - '#797979'
    - '#e5e7e5'
  brandStrength: 1
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
