layout_spectrum: 0.49027215503156185
typography_spectrum: 0.3184486464597285
color:
  brandStrength: 0.5570140797644854
  lightness: 0.9208652735687792
  saturation: 0.12671939842402935
  rhythmicContrast: 0.8163395423907787
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
description: For the love of filmmaking
title: The Open Film School
navigation:
  - id: aa8a1ea0-29c3-449a-8224-d7adb925e58c
    name: 'Documentary '
    type: content
  - id: a6387259-4974-4fa9-b705-44df17fc1956
    name: Screenwriting
    type: content
  - id: 666ea6f1-cac6-45e7-8413-7fdbc44bbde3
    name: Total Filmmaking
    type: content
  - id: 990b0e4d-6bb6-4029-bd58-fbf0c03209c1
    name: About Us
    type: content
cta:
  version: null
  bucket: null
  domain: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8e3f56a4-ebba-454c-a21e-9e6b038cca4c.jpg
name: The  Open  Film  School
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: 'https://www.facebook.com/theopenfilmschool/'
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
