layout_spectrum: 0.25460658874362707
typography_spectrum: 0.3917598647531122
color:
  brandStrength: 0.2502894848585129
  lightness: 0.550281381001696
  saturation: 0.5759696515742689
  rhythmicContrast: 0.6786673308815807
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
description: For the love of filmmaking
title: The Open Film School
navigation:
  - id: aa8a1ea0-29c3-449a-8224-d7adb925e58c
    name: 'Documentary '
    type: content
  - id: a6387259-4974-4fa9-b705-44df17fc1956
    name: Screenwriting
    type: content
  - id: 666ea6f1-cac6-45e7-8413-7fdbc44bbde3
    name: Total Filmmaking
    type: content
  - id: 990b0e4d-6bb6-4029-bd58-fbf0c03209c1
    name: About Us
    type: content
cta:
  version: null
  bucket: null
  domain: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8e3f56a4-ebba-454c-a21e-9e6b038cca4c.jpg
name: The  Open  Film  School
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: 'https://www.facebook.com/theopenfilmschool/'
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
