name: The  Open  Film  School
favicon: null
layout_spectrum: 0.04426
typography_spectrum: 0.00812
title: The Open Film School
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#06011f'
    - '#fcfee6'
    - '#6b5e67'
    - '#a89783'
    - '#cacdba'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
