layout_spectrum: 0.25460658874362707
typography_spectrum: 0.2903591003268957
color:
  brandStrength: 0.18124290998093784
  lightness: 0.6322242510505021
  saturation: 0.9297141556162387
  rhythmicContrast: 0.7146681253798306
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
opengraph:
  image: null
  type: null
  appId: 'https://www.facebook.com/theopenfilmschool/'
analytics:
  twitter: null
  google: null
  facebook: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/9d316da3-17e3-4b1b-80ce-70c5b2260f9a.png
name: The  Open  Film  School
cta:
  version: null
  bucket: null
  domain: null
navigation:
  - name: Total Filmmaking
    id: 666ea6f1-cac6-45e7-8413-7fdbc44bbde3
    type: content
  - name: Screenwriting
    id: a6387259-4974-4fa9-b705-44df17fc1956
    type: content
  - name: 'Documentary '
    id: aa8a1ea0-29c3-449a-8224-d7adb925e58c
    type: content
  - name: Contact Form
    url: 'http://www.123contactform.com/form-2171131/Contact-Lead-Form'
    type: external
  - name: About Us
    id: 990b0e4d-6bb6-4029-bd58-fbf0c03209c1
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8e3f56a4-ebba-454c-a21e-9e6b038cca4c.jpg
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: ''
description: ' As an artist, you get the opportunity to create the world that exists in your fantasies'
purpose: []
