name: The  Open  Film  School
favicon: null
layout_spectrum: 0.24278
typography_spectrum: 0
title: The Open Film School
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#e1d7c7'
    - '#7e95a6'
    - '#475300'
    - '#d7a500'
  brandStrength: 0.5
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
