typography_spectrum: 0.74639
color:
  brandColors:
    - '#00000a'
    - '#dc0c0c'
    - '#dec10d'
    - '#067483'
    - '#06b3ae'
  brandStrength: 0.5
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
name: The  Open  Film  School
cta:
  domain: null
  bucket: null
  version: null
favicon: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: The Open Film School
description: For the love of filmmaking
purpose: []
