name: The  Open  Film  School
favicon: null
layout_spectrum: 0.75361
typography_spectrum: 0.27372882165946066
title: The Open Film School
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#060808'
    - '#c0c1c2'
    - '#656868'
    - '#9fa3a3'
  brandStrength: 0.3780095430556685
  lightness: 0.5231494577601552
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
