name: the open film school
favicon: null
layout_spectrum: 0.26417555031366646
typography_spectrum: 0.27372882165946066
title: The Open Film School
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f0fb00'
    - '#100607'
    - '#fcfcfc'
    - '#f42c1f'
    - '#bbcbca'
  brandStrength: 0.3780095430556685
  lightness: 0.5231494577601552
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
